import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Footer from '../component/Footer'
import Navbar from '../component/Navbar'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
   
      <Head>
        <title>CodesWear.com-Wear the code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
       <img src="/bg3.jpg" alt="error" className='h-[100vh] w-[100vw]'/>
    
    </>
  )
}
